# Install and setup the following components for each system in the following order.
---
macosx:
  - dotfiles
  - homebrew # This need's to run first due to cmd dependency
  - localrc
  - git
  - vim
  - macosx
  - node
  - ruby

linux:
