#!/usr/bin/env zsh
SCRIPT=`realpath $0`
SCRIPTPATH=`dirname $SCRIPT`

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
